
const CHESS_SIZE = 60,
    VICTORY_CONDITION = 5,
    SLASH_DISTANCE = 1.414,
    STRAIGHT_DISTANCE = 1;

export {
    CHESS_SIZE,
    VICTORY_CONDITION,
    SLASH_DISTANCE,
    STRAIGHT_DISTANCE
};
